# -*- coding: utf-8 -*-
"""evaluate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ct5peYs7J1CjMqH-KD-pGjdkOD4grxW2
"""

from google.colab import drive
drive.mount("/content/drive")

import os

PROJECT_ROOT = "/content/drive/MyDrive/Thesis"
os.makedirs(PROJECT_ROOT, exist_ok=True)
os.environ["PROJECT_ROOT"] = PROJECT_ROOT
print("Project root:", PROJECT_ROOT)

!pip install -q \
  "torch==2.4.*" "torchvision==0.19.*" "transformers==4.56.*" \
  "numpy<2" \
  "av>=12" "einops>=0.8" "faiss-cpu>=1.8" "gdown>=5" \
  "matplotlib>=3.9" "opencv-python==4.11.*" "pyyaml>=6" \
  "requests>=2.32" "scikit-learn>=1.5" "torchmetrics>=1.4" "tqdm>=4.66"

import os

DRIVE = '/content/drive/MyDrive/Thesis'
os.environ['KATVAD_DATA_ROOT']   = f'{DRIVE}/data'     # raw videos + label files
os.environ['KATVAD_CACHE_ROOT']  = f'{DRIVE}/cache'    # CLIP / flow / KNN caches
os.environ['KATVAD_CKPT_ROOT']   = f'{DRIVE}/ckpts'    # best.ckpt + our checkpoints
os.environ['KATVAD_OUTPUT_ROOT'] = f'{DRIVE}/outputs'  # eval results, plots, logs
for v in ('KATVAD_DATA_ROOT', 'KATVAD_CACHE_ROOT', 'KATVAD_CKPT_ROOT', 'KATVAD_OUTPUT_ROOT'):
    os.makedirs(os.environ[v], exist_ok=True)

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# 
# python -m core.tools.download clip

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# python -m core.data.msad \
#   --annotation "$KATVAD_DATA_ROOT/MSAD/annotations/anno_eval.tsv" \
#   --out-dir "$KATVAD_DATA_ROOT/MSAD" \
#   --scenarios all --one-indexed --infer-abnormal-from-name \
#   --split-file "$KATVAD_DATA_ROOT/MSAD/annotations/test_ids.txt"

"""## Extract CLIP features"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# 
# python -m core.tools.extract_clip_features \
#   --videos-dir "$KATVAD_DATA_ROOT/MSAD/videos" \
#   --dataset MSAD-full \
#   --no-center-crop \
#   --output-dir "$KATVAD_CACHE_ROOT/clip/MSAD_ncc" \
#   --device cuda

"""## Reproduction baseline LaGoVAD"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# 
# python -m core.evaluate \
#   --baseline-ckpt "$KATVAD_CKPT_ROOT/best.ckpt" \
#   --set kip.enabled=false --set data.dataset=MSAD-full \
#   --data-dir "$KATVAD_DATA_ROOT/MSAD" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/MSAD_ncc" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/MSAD_ncc/full_gate_a" \
#   --save-scores

"""# Visualization"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# 
# python -m core.tools.visualize \
#   --scores "$KATVAD_OUTPUT_ROOT/msad/full_gate_a/scores" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/msad/full_gate_a/plots"

