# -*- coding: utf-8 -*-
"""evaluate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cnUiuXlP5v5kCXafftCAF65vq2Llcp0R
"""

from google.colab import drive
drive.mount("/content/drive")

import os

PROJECT_ROOT = "/content/drive/MyDrive/Thesis"
os.makedirs(PROJECT_ROOT, exist_ok=True)
os.environ["PROJECT_ROOT"] = PROJECT_ROOT
print("Project root:", PROJECT_ROOT)

!pip install -q \
  "torch==2.4.*" "torchvision==0.19.*" "transformers==4.56.*" \
  "numpy<2" \
  "av>=12" "einops>=0.8" "faiss-cpu>=1.8" "gdown>=5" \
  "matplotlib>=3.9" "opencv-python==4.11.*" "pyyaml>=6" \
  "requests>=2.32" "scikit-learn>=1.5" "torchmetrics>=1.4" "tqdm>=4.66"

import os

DRIVE = '/content/drive/MyDrive/Thesis'
os.environ['KATVAD_DATA_ROOT']   = f'{DRIVE}/data'     # raw videos + label files
os.environ['KATVAD_CACHE_ROOT']  = f'{DRIVE}/cache'    # CLIP / flow / KNN caches
os.environ['KATVAD_CKPT_ROOT']   = f'{DRIVE}/ckpts'    # best.ckpt + our checkpoints
os.environ['KATVAD_OUTPUT_ROOT'] = f'{DRIVE}/outputs'  # eval results, plots, logs
for v in ('KATVAD_DATA_ROOT', 'KATVAD_CACHE_ROOT', 'KATVAD_CKPT_ROOT', 'KATVAD_OUTPUT_ROOT'):
    os.makedirs(os.environ[v], exist_ok=True)

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# set -e
# cd /content/drive/MyDrive/Thesis/data/DoTA
# 
# # # 1,402 patterns, one per val clip (~42 KB of argv — well under ARG_MAX)
# # python - <<'PY'
# # ids = [l.strip() for l in open('/content/drive/MyDrive/Thesis/data/DoTA/val_split.txt') if l.strip()]
# # open('/content/drive/MyDrive/Thesis/data/DoTA/patterns.txt','w').write('\n'.join(f'frames/{i}/*' for i in ids))
# # print(len(ids), 'patterns')
# # PY
# 
# # df -h /content/drive/MyDrive/Thesis/data | tail -1   # need ~20 GB free
# # unzip -q "$KATVAD_DATA_ROOT/DoTA/DoTA_full.zip" $(tr '\n' ' ' < patterns.txt) -d /content/drive/MyDrive/Thesis/data/DoTA
# ls /content/drive/MyDrive/Thesis/data/DoTA/frames | wc -l    # expect 1402
# # ls /content/drive/MyDrive/Thesis/data/DoTA/frames/$(ls /content/drive/MyDrive/Thesis/data/DoTA/frames | head -1)/images | head -3

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# 
# python -m core.tools.download clip

import os, subprocess
ROOT = '/content/drive/MyDrive/Thesis/data/DoTA/frames'            # the --frames-dir you passed
ZIP  = os.environ['KATVAD_DATA_ROOT'] + '/DoTA/DoTA_full.zip'
ids  = [l.strip() for l in open(os.environ['KATVAD_DATA_ROOT'] + '/DoTA/val_split.txt') if l.strip()]

on_disk = set(os.listdir(ROOT)) if os.path.isdir(ROOT) else set()
usable  = {d for d in on_disk if os.path.isdir(f'{ROOT}/{d}/images') and os.listdir(f'{ROOT}/{d}/images')}
missing = [i for i in ids if i not in usable]
print(f'split={len(ids)}  folders={len(on_disk)}  usable={len(usable)}  missing={len(missing)}')

# which flavour of unreadable?
absent    = [i for i in missing if i not in on_disk]                       # no folder at all
no_subdir = [i for i in missing if i in on_disk and not os.path.isdir(f'{ROOT}/{i}/images')]
empty     = [i for i in missing if i not in absent and i not in no_subdir] # images/ exists, 0 files
print(f'  absent={len(absent)} {absent[:3]}\n  no images/ subdir={len(no_subdir)} {no_subdir[:3]}'
      f'\n  empty images/={len(empty)} {empty[:3]}')

# is the clip in the archive at all? (reads the central directory only, ~seconds)
names = subprocess.run(['unzip','-Z1',ZIP], capture_output=True, text=True).stdout.splitlines()
in_zip = {n.split('/')[1] for n in names if n.startswith('frames/') and n.count('/') >= 2}
print('clips in zip:', len(in_zip), '| missing AND absent from zip:',
      len([i for i in missing if i not in in_zip]))

open('/content/drive/MyDrive/Thesis/data/DoTA/missing.txt','w').write('\n'.join(missing))

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# 
# python -m core.data.dota \
#   --metadata   "$KATVAD_DATA_ROOT/DoTA/metadata_val.json" \
#   --split-file "$KATVAD_DATA_ROOT/DoTA/val_split.txt" \
#   --frames-dir "$KATVAD_DATA_ROOT/DoTA/frames" --frames-subdir images \
#   --out-dir    "$KATVAD_DATA_ROOT/DoTA/labels_s8" \
#   --stride 8 --allow-missing-frames

"""## Extract CLIP features"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# 
# python -m core.tools.extract_clip_features \
#   --frames-dir "$KATVAD_DATA_ROOT/DoTA/frames" --frames-subdir images \
#   --ids-file "$KATVAD_DATA_ROOT/DoTA/labels_s8/test_ids.txt" \
#   --dataset DoTA --stride 1 --batch-size 64 \
#   --output-dir "$KATVAD_CACHE_ROOT/clip/DoTA_s1"
# 
# # --device cuda

from pathlib import Path
import numpy as np, os

src = Path(os.environ['KATVAD_CACHE_ROOT']) / 'clip' / 'DoTA_s1'
dst = Path(os.environ['KATVAD_CACHE_ROOT']) / 'clip' / 'DoTA_s8'
dst.mkdir(parents=True, exist_ok=True)
for p in src.glob('*.npy'):
    np.save(dst / p.name, np.load(p)[::8])
print(len(list(dst.glob('*.npy'))), 'files')

"""## Reproduction baseline LaGoVAD"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# 
# DATA="$KATVAD_DATA_ROOT/DoTA/labels_s8"
# CLIP="$KATVAD_CACHE_ROOT/clip/DoTA_s8"
# OUT="$KATVAD_OUTPUT_ROOT/DoTA"
# 
# # Arm 1 — reference: LaGoVAD's released checkpoint (PreVAD-trained)
# python -m core.evaluate \
#   --baseline-ckpt "$KATVAD_CKPT_ROOT/best.ckpt" \
#   --set kip.enabled=false --set data.dataset=DoTA \
#   --data-dir "$DATA" --clip-dir "$CLIP" \
#   --output-dir "$OUT/gate_a" --save-scores

"""## MSAD-trained & KIP-off"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# 
# DATA="$KATVAD_DATA_ROOT/DoTA/labels_s8"
# CLIP="$KATVAD_CACHE_ROOT/clip/DoTA_s8"
# OUT="$KATVAD_OUTPUT_ROOT/DoTA"
# 
# # Arm 2 — our baseline (MSAD-trained, KIP off)
# python -m core.evaluate \
#   --ckpt "$KATVAD_OUTPUT_ROOT/MSAD/stage2_kip_off/checkpoint_last.pt" \
#   --set kip.enabled=false --set data.dataset=DoTA \
#   --data-dir "$DATA" --clip-dir "$CLIP" \
#   --output-dir "$OUT/eval_kip_off" --save-scores

"""## MSAD-trained & KIP-on"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# DATA="$KATVAD_DATA_ROOT/DoTA/labels_s8"
# CLIP="$KATVAD_CACHE_ROOT/clip/DoTA_s8"
# OUT="$KATVAD_OUTPUT_ROOT/DoTA"
# 
# # Arm 3 — ours + KIP (MSAD-trained)
# python -m core.evaluate \
#   --ckpt "$KATVAD_OUTPUT_ROOT/MSAD/stage2_kip_on/checkpoint_last.pt" \
#   --set data.dataset=DoTA \
#   --data-dir "$DATA" --clip-dir "$CLIP" \
#   --output-dir "$OUT/eval_kip_on" --save-scores

"""# Visualization"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# 
# python -m core.tools.visualize \
#   --scores "$KATVAD_OUTPUT_ROOT/msad/full_gate_a/scores" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/msad/full_gate_a/plots"

