# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L01mooNH_g5T4i2kqsjUwfcP2GDN91yW
"""

from google.colab import drive
drive.mount("/content/drive")

import os

PROJECT_ROOT = "/content/drive/MyDrive/Thesis"
os.makedirs(PROJECT_ROOT, exist_ok=True)
os.environ["PROJECT_ROOT"] = PROJECT_ROOT
print("Project root:", PROJECT_ROOT)

!pip install -q \
  "torch==2.4.*" "torchvision==0.19.*" "transformers==4.56.*" \
  "numpy<2" \
  "av>=12" "einops>=0.8" "faiss-cpu>=1.8" "gdown>=5" \
  "matplotlib>=3.9" "opencv-python==4.11.*" "pyyaml>=6" \
  "requests>=2.32" "scikit-learn>=1.5" "torchmetrics>=1.4" "tqdm>=4.66"

import os

DRIVE = '/content/drive/MyDrive/Thesis'
os.environ['KATVAD_DATA_ROOT']   = f'{DRIVE}/data'     # raw videos + label files
os.environ['KATVAD_CACHE_ROOT']  = f'{DRIVE}/cache'    # CLIP / flow / KNN caches
os.environ['KATVAD_CKPT_ROOT']   = f'{DRIVE}/ckpts'    # best.ckpt + our checkpoints
os.environ['KATVAD_OUTPUT_ROOT'] = f'{DRIVE}/outputs'  # eval results, plots, logs
for v in ('KATVAD_DATA_ROOT', 'KATVAD_CACHE_ROOT', 'KATVAD_CKPT_ROOT', 'KATVAD_OUTPUT_ROOT'):
    os.makedirs(os.environ[v], exist_ok=True)

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# 
# # python -m core.tools.download clip
# python -m core.tools.download raft

"""# Proprocessing"""

# Copy to VM disk for faster decoding
!mkdir -p /content/videos
!cp -rn "$KATVAD_DATA_ROOT/MSAD/videos/"* /content/videos/ 2>/dev/null || true

"""## Build label files"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# 
# python -m core.data.msad \
#   --annotation "$KATVAD_DATA_ROOT/MSAD/annotations/anno_train_full.tsv" \
#   --out-dir "$KATVAD_DATA_ROOT/MSAD" \
#   --scenarios all --one-indexed --infer-abnormal-from-name \
#   --split-file "$KATVAD_DATA_ROOT/MSAD/annotations/test_ids.txt"

"""## Extract CLIP features"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# 
# python -m core.tools.extract_clip_features \
#   --videos-dir "$KATVAD_DATA_ROOT/MSAD/videos" \
#   --dataset MSAD-full \
#   --no-center-crop \
#   --output-dir "$KATVAD_CACHE_ROOT/clip/MSAD_ncc" \
#   --device cuda

"""## Extract RAFT flow"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# 
# python -m core.flow.raft_extract \
#   --videos-dir "$KATVAD_DATA_ROOT/MSAD/videos" \
#   --dataset MSAD-full \
#   --cache-root "$KATVAD_CACHE_ROOT/flow/v1/MSAD" \
#   --device cuda

"""## Build KNN DVS cache"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# 
# python -m core.data.knn_cache \
#   --data-dir "$KATVAD_DATA_ROOT/MSAD" \
#   --dataset MSAD-full \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/MSAD_ncc" \
#   --output "$KATVAD_CACHE_ROOT/knn/MSAD_ncc/knn_cache.npz"

"""# Training

## Stage 1 - KIP only warm-up
"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# 
# S=2025
# python -m core.train \
#   --set train.stage=1 --set data.dataset=MSAD-full \
#   --set train.num_epochs=125 \
#   --set train.seed=$S \
#   --data-dir  "$KATVAD_DATA_ROOT/MSAD" \
#   --clip-dir  "$KATVAD_CACHE_ROOT/clip/MSAD_ncc" \
#   --flow-dir  "$KATVAD_CACHE_ROOT/flow/v1/MSAD/MSAD-full" \
#   --knn-cache "$KATVAD_CACHE_ROOT/knn/MSAD_ncc/knn_cache.npz" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/MSAD_ncc_s$S/stage1"

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# 
# S=2026
# python -m core.train \
#   --set train.stage=1 --set data.dataset=MSAD-full \
#   --set train.num_epochs=125 \
#   --set train.seed=$S \
#   --data-dir  "$KATVAD_DATA_ROOT/MSAD" \
#   --clip-dir  "$KATVAD_CACHE_ROOT/clip/MSAD_ncc" \
#   --flow-dir  "$KATVAD_CACHE_ROOT/flow/v1/MSAD/MSAD-full" \
#   --knn-cache "$KATVAD_CACHE_ROOT/knn/MSAD_ncc/knn_cache.npz" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/MSAD_ncc_s$S/stage1"

"""## KIP on"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# 
# S=2025
# 
# python -m core.train \
#   --set train.stage=2 --set train.amp=true \
#   --set data.dataset=MSAD-full \
#   --set train.num_epochs=125 \
#   --set train.checkpoint_every_steps=100 \
#   --set train.seed=$S \
#   --init-weights "$KATVAD_OUTPUT_ROOT/MSAD_ncc_s$S/stage1/checkpoint_last.pt" \
#   --data-dir "$KATVAD_DATA_ROOT/MSAD" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/MSAD_ncc" \
#   --flow-dir "$KATVAD_CACHE_ROOT/flow/v1/MSAD/MSAD-full" \
#   --knn-cache "$KATVAD_CACHE_ROOT/knn/MSAD_ncc/knn_cache.npz" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/MSAD_ncc_s$S/stage2_kip_on"

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# 
# S=2026
# 
# python -m core.train \
#   --set train.stage=2 --set train.amp=true \
#   --set data.dataset=MSAD-full \
#   --set train.num_epochs=125 \
#   --set train.checkpoint_every_steps=100 \
#   --set train.seed=$S \
#   --init-weights "$KATVAD_OUTPUT_ROOT/MSAD_ncc_s$S/stage1/checkpoint_last.pt" \
#   --data-dir "$KATVAD_DATA_ROOT/MSAD" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/MSAD_ncc" \
#   --flow-dir "$KATVAD_CACHE_ROOT/flow/v1/MSAD/MSAD-full" \
#   --knn-cache "$KATVAD_CACHE_ROOT/knn/MSAD_ncc/knn_cache.npz" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/MSAD_ncc_s$S/stage2_kip_on"

"""## KIP off - Baseline"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# 
# S=2025
# python -m core.train \
#   --set train.stage=2 --set train.amp=true \
#   --set kip.enabled=false \
#   --set data.dataset=MSAD-full \
#   --set train.num_epochs=125 \
#   --set train.checkpoint_every_steps=100 \
#   --set train.seed=$S \
#   --data-dir "$KATVAD_DATA_ROOT/MSAD" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/MSAD_ncc" \
#   --knn-cache "$KATVAD_CACHE_ROOT/knn/MSAD_ncc/knn_cache.npz" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/MSAD_ncc_s$S/stage2_kip_off"
#

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# 
# S=2026
# python -m core.train \
#   --set train.stage=2 --set train.amp=true \
#   --set kip.enabled=false \
#   --set data.dataset=MSAD-full \
#   --set train.num_epochs=125 \
#   --set train.checkpoint_every_steps=100 \
#   --set train.seed=$S \
#   --data-dir "$KATVAD_DATA_ROOT/MSAD" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/MSAD_ncc" \
#   --knn-cache "$KATVAD_CACHE_ROOT/knn/MSAD_ncc/knn_cache.npz" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/MSAD_ncc_s$S/stage2_kip_off"

"""# Evaluation

## Baseline
"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# 
# S=2025
# python -m core.evaluate \
#   --ckpt "$KATVAD_OUTPUT_ROOT/MSAD_ncc_s$S/stage2_kip_off/checkpoint_last.pt" \
#   --set kip.enabled=false --set data.dataset=MSAD-full \
#   --data-dir "$KATVAD_DATA_ROOT/MSAD" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/MSAD_ncc" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/MSAD_ncc_s$S/eval_kip_off" \
#   --save-scores

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# 
# S=2026
# python -m core.evaluate \
#   --ckpt "$KATVAD_OUTPUT_ROOT/MSAD_ncc_s$S/stage2_kip_off/checkpoint_last.pt" \
#   --set kip.enabled=false --set data.dataset=MSAD-full \
#   --data-dir "$KATVAD_DATA_ROOT/MSAD" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/MSAD_ncc" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/MSAD_ncc_s$S/eval_kip_off" \
#   --save-scores

"""## KIP on"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# 
# S=2025
# 
# python -m core.evaluate \
#   --ckpt "$KATVAD_OUTPUT_ROOT/MSAD_ncc_s$S/stage2_kip_on/checkpoint_last.pt" \
#   --set data.dataset=MSAD-full \
#   --data-dir "$KATVAD_DATA_ROOT/MSAD" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/MSAD_ncc" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/MSAD_ncc_s$S/eval_kip_on" \
#   --save-scores

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# 
# S=2026
# 
# python -m core.evaluate \
#   --ckpt "$KATVAD_OUTPUT_ROOT/MSAD_ncc_s$S/stage2_kip_on/checkpoint_last.pt" \
#   --set data.dataset=MSAD-full \
#   --data-dir "$KATVAD_DATA_ROOT/MSAD" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/MSAD_ncc" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/MSAD_ncc_s$S/eval_kip_on" \
#   --save-scores

"""# Visualization

## Baseline
"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# 
# python -m core.tools.visualize \
#   --scores "$KATVAD_OUTPUT_ROOT/MSAD_ncc/eval_kip_off/scores" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/MSAD_ncc/eval_kip_off/plots"

"""## KIP on"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# 
# python -m core.tools.visualize \
#   --scores "$KATVAD_OUTPUT_ROOT/MSAD_ncc/eval_kip_on/scores" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/MSAD_ncc/eval_kip_on/plots"

"""# Per-class KIP breakdown"""

import json, os, re
from collections import defaultdict

out = os.environ['KATVAD_OUTPUT_ROOT']
res = {k: json.load(open(f'{out}/MSAD_ncc/eval_kip_{k}/results.json'))['per_video']
       for k in ('off', 'on')}
by_cls = defaultdict(list)
for vid, r in res['off'].items():
    if r['abnormal']:
        cls = re.sub(r'_\d+$', '', vid)
        by_cls[cls].append(res['on'][vid]['max_score'] - r['max_score'])
for cls, deltas in sorted(by_cls.items(), key=lambda kv: -sum(kv[1]) / len(kv[1])):
    print(f'{cls:20s} n={len(deltas):3d}  mean Δmax_score {sum(deltas)/len(deltas):+.3f}')

