# -*- coding: utf-8 -*-
"""phase_0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DW840VeRs8Mvwk__eiB-BJZW94wJpyo8

# Train on DADA dataset
"""

from google.colab import drive
drive.mount("/content/drive")

import os

PROJECT_ROOT = "/content/drive/MyDrive/Thesis"
os.makedirs(PROJECT_ROOT, exist_ok=True)
os.environ["PROJECT_ROOT"] = PROJECT_ROOT
print("Project root:", PROJECT_ROOT)

import os

DRIVE = '/content/drive/MyDrive/Thesis'

os.environ['KATVAD_DATA_ROOT']   = f'{DRIVE}/data'
os.environ['KATVAD_CACHE_ROOT']  = f'{DRIVE}/cache'
os.environ['KATVAD_CKPT_ROOT']   = f'{DRIVE}/ckpts'
os.environ['KATVAD_OUTPUT_ROOT'] = f'{DRIVE}/outputs'
for v in ('KATVAD_DATA_ROOT', 'KATVAD_CACHE_ROOT', 'KATVAD_CKPT_ROOT', 'KATVAD_OUTPUT_ROOT'):
    os.makedirs(os.environ[v], exist_ok=True)

import os
os.environ['DADA_ORIG'] = f"{os.environ['KATVAD_DATA_ROOT']}/DADA2000Origin/DADA2000"
os.environ['PROBE']     = '/content/probe'          # VM-local NVMe, never Drive
os.makedirs(os.environ['PROBE'], exist_ok=True)

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# apt-get -qq install -y p7zip-full
# pip install -q openpyxl        # Colab usually has it; the project venv does not
# ls -la "$DADA_ORIG"
# df -h /content | tail -1       # how much VM disk you actually have
# du -ch "$DADA_ORIG"/DADA2000.z* | tail -1   # total archive size

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd "$DADA_ORIG"
# 7z l DADA2000.zip | head -60
# echo '--- entry count ---'
# 7z l DADA2000.zip | tail -3

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd "$DADA_ORIG"
# # distinct top-level and second-level path prefixes
# 7z l -slt DADA2000.zip | grep '^Path = ' | sed 's/^Path = //' \
#   | awk -F/ '{print $1"/"$2}' | sort -u | head -40

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd "$DADA_ORIG"
# time 7z l -slt DADA2000.zip | grep -E '^(Path|Size) = ' > /content/listing.txt
# wc -l /content/listing.txt

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# # (a) các subdir bên trong 1 clip = frame RGB nằm ở đâu?
# python - <<'PY'
# import collections, re
# sub = collections.Counter(); size = collections.Counter(); path = None
# for line in open('/content/listing.txt', encoding='utf-8', errors='replace'):
#     if line.startswith('Path = '):
#         path = line[7:].strip()
#     elif line.startswith('Size = ') and path:
#         parts = path.split('/')
#         if len(parts) >= 4:
#             sub[parts[3]] += 1
#             size[parts[3]] += int(line[7:].strip() or 0)
#         path = None
# print(f"{'subdir':16s} {'#files':>10s} {'GiB':>9s}")
# for k, n in sub.most_common():
#     print(f'{k:16s} {n:10d} {size[k]/2**30:9.2f}')
# PY

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# # (b) danh sách type ĐẦY ĐỦ (không head), để đối chiếu 52 type của xlsx
# python - <<'PY'
# import re
# types = set()
# for line in open('/content/listing.txt', encoding='utf-8', errors='replace'):
#     if line.startswith('Path = '):
#         p = line[7:].strip().split('/')
#         if len(p) >= 2 and p[1].isdigit():
#             types.add(int(p[1]))
# print(f'{len(types)} types on disk:', sorted(types))
# PY

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/pick_probe.py
# """Pick a type-stratified probe sample from the DADA-2000 annotation.
# 
# The sheet is **detected**, not hardcoded: this workbook is a hand-maintained
# export and its sheet names and header spelling are not a contract. On failure the
# script prints every sheet's header so the mismatch is visible in one run.
# """
# from __future__ import annotations
# import argparse, json, random, re, sys
# from pathlib import Path
# from openpyxl import load_workbook
# 
# REQUIRED = ("type", "video", "abnormal start frame",
#             "abnormal end frame", "total frames")
# COL_ACCIDENT = "whether an accident occurred (1/0)"
# 
# 
# def norm(value: object) -> str:
#     """Case/whitespace-insensitive header key (the file uses NBSP in places)."""
#     if value is None:
#         return ""
#     return re.sub(r"\s+", " ", str(value).replace("\xa0", " ")).strip().lower()
# 
# 
# def find_sheet(xlsx: Path) -> tuple[list[tuple], list[str]]:
#     """``(rows, header)`` for the first sheet carrying every REQUIRED column."""
#     wb = load_workbook(xlsx, read_only=True, data_only=True)
#     seen: list[tuple[str, list[str]]] = []
#     for name in wb.sheetnames:
#         it = wb[name].iter_rows(values_only=True)
#         try:
#             header = [norm(c) for c in next(it)]
#         except StopIteration:
#             seen.append((name, []))
#             continue
#         seen.append((name, header))
#         if all(norm(col) in header for col in REQUIRED):
#             print(f"sheet: {name!r}  ({len(header)} columns)")
#             return list(it), header
#     lines = [f"  [{n}] {h}" for n, h in seen]
#     sys.exit(
#         f"No sheet in {xlsx} carries all of {REQUIRED}.\nSheets found:\n"
#         + "\n".join(lines)
#     )
# 
# 
# def read_rows(xlsx: Path) -> list[dict]:
#     body, header = find_sheet(xlsx)
#     idx = {c: header.index(norm(c)) for c in REQUIRED}
#     acc = header.index(norm(COL_ACCIDENT)) if norm(COL_ACCIDENT) in header else None
#     if acc is None:
#         print(f"WARNING: no {COL_ACCIDENT!r} column; treating every row with a "
#               "valid window as an accident row")
#     out: list[dict] = []
#     for raw in body:
#         def cell(i: int) -> object:
#             return raw[i] if i < len(raw) else None
#         if acc is not None and str(cell(acc)).strip() != "1":
#             continue
#         try:
#             typ, vid = int(cell(idx["type"])), int(cell(idx["video"]))
#             start = int(cell(idx["abnormal start frame"]))
#             end = int(cell(idx["abnormal end frame"]))
#             total = int(cell(idx["total frames"]))
#         except (TypeError, ValueError):
#             continue
#         if not 0 <= start < end <= total:
#             continue
#         out.append({"type": typ, "video": vid, "start": start,
#                     "end": end, "total": total})
#     return out
# 
# 
# def main(argv: list[str] | None = None) -> None:
#     ap = argparse.ArgumentParser()
#     ap.add_argument("--xlsx", type=Path, required=True)
#     ap.add_argument("--n", type=int, default=30)
#     ap.add_argument("--seed", type=int, default=2024)
#     ap.add_argument("--out", type=Path, required=True)
#     args = ap.parse_args(argv)
# 
#     rows = read_rows(args.xlsx)
#     if not rows:
#         sys.exit("No valid accident rows parsed -- check the sheet name")
#     by_type: dict[int, list[dict]] = {}
#     for r in rows:
#         by_type.setdefault(r["type"], []).append(r)
# 
#     rng = random.Random(args.seed)
#     picked: list[dict] = []
#     for typ in sorted(by_type):                       # one per type first
#         picked.append(rng.choice(by_type[typ]))
#     rng.shuffle(picked)
#     picked = picked[: args.n]
#     args.out.write_text(json.dumps(picked, indent=2), encoding="utf-8")
#     print(f"{len(rows)} annotated clips over {len(by_type)} types "
#           f"-> picked {len(picked)}")
#     for r in picked[:5]:
#         print("  ", r)
# 
# 
# if __name__ == "__main__":
#     main()

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# python /content/pick_probe.py \
#   --xlsx "$DADA_ORIG/dada标注.xlsx" --n 30 --seed 2024 \
#   --out /content/probe_clips.json

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# set -e
# cd "$DADA_ORIG"
# python - <<'PY' > /content/probe_patterns.txt
# import json
# PAT = "DADA2000/{t}/{v:03d}/images/*"     # measured layout, see section 3.1
# for r in json.load(open('/content/probe_clips.json')):
#     print(PAT.format(t=r['type'], v=r['video']))
# PY
# wc -l /content/probe_patterns.txt          # expect 30
# head -3 /content/probe_patterns.txt
# 
# 7z x DADA2000.zip -o"$PROBE" -y $(tr '\n' ' ' < /content/probe_patterns.txt)
# du -sh "$PROBE"                            # expect ~1.5 GB (30 x ~49 MiB)
# find "$PROBE" -mindepth 3 -maxdepth 3 -type d | wc -l   # expect 30

"""# P1 - Hard Gate"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/check_p1.py
# """P1: does the annotation's `total frames` match the real frame count?"""
# from __future__ import annotations
# import argparse, json, subprocess
# from pathlib import Path
# 
# IMAGE_SUFFIXES = {".png", ".jpg", ".jpeg", ".bmp"}
# VIDEO_SUFFIXES = {".mp4", ".avi", ".mov", ".mkv"}
# 
# 
# def count_images(folder: Path) -> int:
#     return sum(1 for p in folder.iterdir() if p.suffix.lower() in IMAGE_SUFFIXES)
# 
# 
# def count_video_frames(path: Path) -> int:
#     out = subprocess.run(
#         ["ffprobe", "-v", "error", "-count_frames", "-select_streams", "v:0",
#          "-show_entries", "stream=nb_read_frames", "-of", "csv=p=0", str(path)],
#         capture_output=True, text=True, check=True,
#     ).stdout.strip()
#     return int(out) if out.isdigit() else -1
# 
# 
# def main() -> None:
#     ap = argparse.ArgumentParser()
#     ap.add_argument("--clips", type=Path, required=True)
#     ap.add_argument("--root", type=Path, required=True)
#     ap.add_argument("--template", required=True,
#                     help="path under --root, e.g. 'DADA2000/{t}/{v:03d}/images'")
#     ap.add_argument("--tolerance", type=int, default=2)
#     args = ap.parse_args()
# 
#     rows = json.loads(args.clips.read_text(encoding="utf-8"))
#     checked = matched = missing = 0
#     deltas: list[tuple[str, int, int]] = []
#     for r in rows:
#         rel = args.template.format(t=r["type"], v=r["video"])
#         target = args.root / rel
#         if target.is_dir():
#             real = count_images(target)
#         elif target.is_file() and target.suffix.lower() in VIDEO_SUFFIXES:
#             real = count_video_frames(target)
#         else:
#             cand = [p for p in (args.root / rel).parent.glob(f"{Path(rel).name}*")
#                     if p.suffix.lower() in VIDEO_SUFFIXES] if (args.root / rel).parent.is_dir() else []
#             if len(cand) == 1:
#                 real = count_video_frames(cand[0])
#             else:
#                 missing += 1
#                 continue
#         checked += 1
#         delta = real - r["total"]
#         if abs(delta) <= args.tolerance:
#             matched += 1
#         else:
#             deltas.append((rel, r["total"], real))
# 
#     print(f"checked   {checked}   missing on disk {missing}")
#     if checked:
#         print(f"matched within +-{args.tolerance}: {matched}/{checked} "
#               f"({100 * matched / checked:.1f}%)")
#     if deltas:
#         print(f"\n{'clip':34s} {'annotation':>10s} {'on disk':>8s} {'delta':>7s}")
#         for rel, ann, real in sorted(deltas, key=lambda d: abs(d[2] - d[1]))[:20]:
#             print(f"{rel:34s} {ann:10d} {real:8d} {real - ann:+7d}")
#         mean = sum(r - a for _, a, r in deltas) / len(deltas)
#         print(f"\nmean signed delta over mismatches: {mean:+.1f}")
#         print("A systematic one-sided delta means the clips were TRIMMED, not "
#               "merely re-encoded -- the fraction mapping in "
#               "core/data/dada.py:296 is then WRONG. See plan section 3.")
# 
# 
# if __name__ == "__main__":
#     main()

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# python /content/check_p1.py \
#   --clips /content/probe_clips.json \
#   --root "$PROBE" \
#   --template 'DADA2000/{t}/{v:03d}/images' \
#   --tolerance 2

!pip install av

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# python - <<'PY'
# import json, itertools
# from pathlib import Path
# from core.tools.extract_clip_features import preprocess_frames
# from core.data.video_io import list_frame_images, read_images
# 
# root = Path('/content/probe')
# rows = json.loads(Path('/content/probe_clips.json').read_text())
# ok = bad = 0
# for r in itertools.islice(rows, 5):
#     folder = root / f"DADA2000/{r['type']}/{r['video']:03d}/images"
#     if not folder.is_dir():
#         print('skip (layout)', folder); continue
#     paths = list_frame_images(folder)[:8]
#     try:
#         frames = read_images(paths)                   # (N, H, W, 3) uint8
#         batch = preprocess_frames(frames, center_crop=False)   # <-- _ncc, see below
#         print(f"{folder.name}: {len(paths)} frames, native {frames.shape[1:3]} "
#               f"-> {tuple(batch.shape)} {batch.dtype} "
#               f"range[{batch.min():.3f},{batch.max():.3f}]")
#         ok += 1
#     except Exception as exc:                      # probe only; report, don't mask
#         print('FAIL', folder, type(exc).__name__, exc); bad += 1
# print(f"\nP3: {ok} ok, {bad} failed")
# PY

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# mkdir -p "$KATVAD_OUTPUT_ROOT/EDA/DADA2000Origin"
# cp /content/probe_clips.json "$KATVAD_OUTPUT_ROOT/EDA/DADA2000Origin/"



