# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10U2YdJBREgOSG8iPI0fX7h_hc-XiJHof

# Train on DADA dataset
"""

from google.colab import drive
drive.mount("/content/drive")

import os

PROJECT_ROOT = "/content/drive/MyDrive/Thesis"
os.makedirs(PROJECT_ROOT, exist_ok=True)
os.environ["PROJECT_ROOT"] = PROJECT_ROOT
print("Project root:", PROJECT_ROOT)

!pip install -q \
  "transformers==4.56.*" \
  "av>=12" "einops>=0.8" "faiss-cpu==1.14.3" "gdown>=5" \
  "matplotlib>=3.9" "opencv-python==4.11.*" "pyyaml>=6" \
  "requests>=2.32" "scikit-learn>=1.5" "torchmetrics>=1.4" "tqdm>=4.66"

import faiss, numpy, torch, transformers
from transformers import CLIPTextModel
print('torch', torch.__version__, '| transformers', transformers.__version__,
      '| numpy', numpy.__version__, '| faiss', faiss.__version__)
print('text_model present:', 'text_model' in CLIPTextModel.__init__.__code__.co_names)

import os

DRIVE = '/content/drive/MyDrive/Thesis'
DRIVE_V3 = '/content/drive/MyDrive/Thesis-V3'


os.environ['KATVAD_DATA_ROOT']   = f'{DRIVE}/data'
os.environ['KATVAD_CACHE_ROOT']  = f'{DRIVE}/cache'
os.environ['KATVAD_CKPT_ROOT']   = f'{DRIVE}/ckpts'
os.environ['KATVAD_OUTPUT_ROOT'] = f'{DRIVE}/outputs'
os.environ['KATVAD_OUTPUT_ROOT_V3'] = f'{DRIVE_V3}/outputs'
for v in ('KATVAD_DATA_ROOT', 'KATVAD_OUTPUT_ROOT_V3', 'KATVAD_CACHE_ROOT', 'KATVAD_CKPT_ROOT', 'KATVAD_OUTPUT_ROOT'):
    os.makedirs(os.environ[v], exist_ok=True)

"""# Training

## KIP-off
"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# S=2024 ; E=20
# 
# python -m core.train \
#   --set train.stage=2 --set train.amp=true --set data.dataset=DADA2000 \
#   --set data.is_egocentric=true \
#   --set train.num_epochs=$E --set train.checkpoint_every_steps=400 \
#   --set train.seed=$S \
#   --set kip.enabled=false \
#   --data-dir  "$KATVAD_DATA_ROOT/DADA2000" \
#   --clip-dir  "$KATVAD_CACHE_ROOT/clip/DADA2000" \
#   --knn-cache "$KATVAD_CACHE_ROOT/knn/DADA2000/knn_cache.npz" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/DADA2000/$S/kipoff/stage2"

"""## P1 Control"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# S=2024 ; E=20
# 
# COMMON="--set train.stage=2 --set train.amp=true --set data.dataset=DADA2000 \
#   --set data.is_egocentric=true \
#   --set train.num_epochs=$E --set train.checkpoint_every_steps=400 \
#   --set train.seed=$S --set kip.enabled=false \
#   --data-dir  $KATVAD_DATA_ROOT/DADA2000 \
#   --clip-dir  $KATVAD_CACHE_ROOT/clip/DADA2000 \
#   --knn-cache $KATVAD_CACHE_ROOT/knn/DADA2000/knn_cache.npz"
# 
# python -m core.train $COMMON \
#   --output-dir "$KATVAD_OUTPUT_ROOT/DADA2000/$S/p1_ctrl/stage2"

"""## DVS Ignore"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# S=2024 ; E=20
# 
# COMMON="--set train.stage=2 --set train.amp=true --set data.dataset=DADA2000 \
#   --set data.is_egocentric=true \
#   --set train.num_epochs=$E --set train.checkpoint_every_steps=100 \
#   --set train.seed=$S --set kip.enabled=false \
#   --data-dir  $KATVAD_DATA_ROOT/DADA2000 \
#   --clip-dir  $KATVAD_CACHE_ROOT/clip/DADA2000 \
#   --knn-cache $KATVAD_CACHE_ROOT/knn/DADA2000/knn_cache.npz"
# 
# # P1 — 1.1, DVS anchor interior ignored (lesson C29)
# python -m core.train $COMMON \
#   --set loss.dvs_anchor_mode=ignore \
#   --output-dir "$KATVAD_OUTPUT_ROOT/DADA2000/$S/p1_dvsignore/stage2"

"""## P1 Bottom K"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# S=2024 ; E=20
# 
# COMMON="--set train.stage=2 --set train.amp=true --set data.dataset=DADA2000 \
#   --set data.is_egocentric=true \
#   --set train.num_epochs=$E --set train.checkpoint_every_steps=100 \
#   --set train.seed=$S --set kip.enabled=false \
#   --data-dir  $KATVAD_DATA_ROOT/DADA2000 \
#   --clip-dir  $KATVAD_CACHE_ROOT/clip/DADA2000 \
#   --knn-cache $KATVAD_CACHE_ROOT/knn/DADA2000/knn_cache.npz"
# 
# python -m core.train $COMMON \
#   --set loss.bottomk_weight=1.0 --set loss.bottomk_topk_pct=16 \
#   --output-dir "$KATVAD_OUTPUT_ROOT/DADA2000/$S/p1_bottomk/stage2"

"""## Both"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# S=2024 ; E=20
# 
# COMMON="--set train.stage=2 --set train.amp=true --set data.dataset=DADA2000 \
#   --set data.is_egocentric=true \
#   --set train.num_epochs=$E --set train.checkpoint_every_steps=100 \
#   --set train.seed=$S --set kip.enabled=false \
#   --data-dir  $KATVAD_DATA_ROOT/DADA2000 \
#   --clip-dir  $KATVAD_CACHE_ROOT/clip/DADA2000 \
#   --knn-cache $KATVAD_CACHE_ROOT/knn/DADA2000/knn_cache.npz"
# 
# python -m core.train $COMMON \
#   --set loss.dvs_anchor_mode=ignore \
#   --set loss.bottomk_weight=1.0 --set loss.bottomk_topk_pct=16 \
#   --output-dir "$KATVAD_OUTPUT_ROOT/DADA2000/$S/p1_both/stage2"

"""# Evaluation

## Baseline KIP-off
"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# S=2024
# CKPT="$KATVAD_OUTPUT_ROOT_V3/DADA2000/kipoff_s$S/stage2/checkpoint_last.pt"
# 
# python -m core.evaluate --ckpt "$CKPT" --set kip.enabled=false \
#   --set data.dataset=DADA2000 \
#   --data-dir "$KATVAD_DATA_ROOT/DADA2000" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/DADA2000" \
#   --score-norm auto --save-scores \
#   --equalize-length 5 --equalize-anchor end \
#   --output-dir "$KATVAD_OUTPUT_ROOT/DADA2000/$S/kipoff/eval_dada_eq5"

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# S=2024
# D="$KATVAD_OUTPUT_ROOT/DADA2000/$S/p1_dvsignore"
# CKPT="$D/stage2/checkpoint_last.pt"
# GATE="--set kip.enabled=false"
# 
# # # (a) in-domain, uncontrolled — for comparison with the existing table only
# # python -m core.evaluate --ckpt "$CKPT" $GATE --set data.dataset=DADA2000 \
# #   --data-dir "$KATVAD_DATA_ROOT/DADA2000" \
# #   --clip-dir "$KATVAD_CACHE_ROOT/clip/DADA2000" \
# #   --score-norm auto --save-scores --output-dir "$D/eval_dada"
# 
# # (b) in-domain, LENGTH-CONTROLLED — the number that means something
# python -m core.evaluate --ckpt "$CKPT" $GATE --set data.dataset=DADA2000 \
#   --data-dir "$KATVAD_DATA_ROOT/DADA2000" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/DADA2000" \
#   --score-norm auto --save-scores \
#   --equalize-length 5 --equalize-anchor end \
#   --output-dir "$D/eval_dada_eq5"
# 
# # # (c) zero-shot DoTA — the honest generalization column
# # python -m core.evaluate --ckpt "$CKPT" $GATE --set data.dataset=DoTA \
# #   --data-dir "$KATVAD_DATA_ROOT/DoTA/labels_s8" \
# #   --clip-dir "$KATVAD_CACHE_ROOT/clip/DoTA_s8_ncc" \
# #   --score-norm auto --save-scores --output-dir "$D/eval_dota"

