# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/151n3zehQsIk-z6hab6VomiH4wMN5qv6i
"""

from google.colab import drive
drive.mount("/content/drive")

import os

PROJECT_ROOT = "/content/drive/MyDrive/Thesis"
os.makedirs(PROJECT_ROOT, exist_ok=True)
os.environ["PROJECT_ROOT"] = PROJECT_ROOT
print("Project root:", PROJECT_ROOT)

!pip install -q \
  "transformers==4.56.*" \
  "av>=12" "einops>=0.8" "faiss-cpu==1.14.3" "gdown>=5" \
  "matplotlib>=3.9" "opencv-python==4.11.*" "pyyaml>=6" \
  "requests>=2.32" "scikit-learn>=1.5" "torchmetrics>=1.4" "tqdm>=4.66"

import faiss, numpy, torch, transformers
from transformers import CLIPTextModel
print('torch', torch.__version__, '| transformers', transformers.__version__,
      '| numpy', numpy.__version__, '| faiss', faiss.__version__)
print('text_model present:', 'text_model' in CLIPTextModel.__init__.__code__.co_names)

import os

DRIVE = '/content/drive/MyDrive/Thesis'
DRIVE_V3 = '/content/drive/MyDrive/Thesis-V3'

os.environ['KATVAD_DATA_ROOT']   = f'{DRIVE}/data'
os.environ['KATVAD_CACHE_ROOT']  = f'{DRIVE}/cache'
os.environ['KATVAD_CKPT_ROOT']   = f'{DRIVE}/ckpts'
os.environ['KATVAD_OUTPUT_ROOT'] = f'{DRIVE_V3}/outputs'
for v in ('KATVAD_DATA_ROOT', 'KATVAD_CACHE_ROOT', 'KATVAD_CKPT_ROOT', 'KATVAD_OUTPUT_ROOT'):
    os.makedirs(os.environ[v], exist_ok=True)

"""# Training

## Stage 1 - KIP only warm-up

### Parameter free-family - Serve A1 and A2b
"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# 
# S=2024; GATE=rank
# python -m core.train \
#   --set train.stage=1 --set data.dataset=MSAD-full \
#   --set train.num_epochs=125 --set train.seed=$S \
#   --set kip.gate_type=$GATE \
#   --data-dir  "$KATVAD_DATA_ROOT/MSAD" \
#   --clip-dir  "$KATVAD_CACHE_ROOT/clip/MSAD_ncc" \
#   --flow-dir  "$KATVAD_CACHE_ROOT/flow/v1/MSAD/MSAD-full" \
#   --knn-cache "$KATVAD_CACHE_ROOT/knn/MSAD_ncc/knn_cache.npz" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/MSAD_${GATE}_s$S/stage1"

"""### MLP Frozen - MLP-family - Serve A3 and A4"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# S=2024
# 
# python -m core.train \
#   --set train.stage=1 --set data.dataset=MSAD-full \
#   --set train.num_epochs=125 --set train.seed=$S \
#   --set kip.gate_type=mlp_frozen --set kip.gate_signal=flow_norm \
#   --data-dir  "$KATVAD_DATA_ROOT/MSAD" \
#   --clip-dir  "$KATVAD_CACHE_ROOT/clip/MSAD_ncc" \
#   --flow-dir  "$KATVAD_CACHE_ROOT/flow/v1/MSAD/MSAD-full" \
#   --knn-cache "$KATVAD_CACHE_ROOT/knn/MSAD_ncc/knn_cache.npz" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/MSAD_mlp_frozen_s$S/stage1"

import json, pathlib, os
p = pathlib.Path(os.environ['KATVAD_OUTPUT_ROOT'])/'MSAD_mlp_frozen_s2024'/'stage1'/'metrics.jsonl'
rows = [json.loads(l) for l in p.read_text().splitlines() if l.strip()]
rec = [r['kip_rec'] for r in rows if 'kip_rec' in r]
print('first 20 mean', sum(rec[:20])/20, '| last 50 mean', sum(rec[-50:])/50)

import json, pathlib, os
FAM = 'rank'          # or 'mlp_frozen'
S = 2024
p = (pathlib.Path(os.environ['KATVAD_OUTPUT_ROOT'])
     / f'MSAD_{FAM}_s{S}' / 'stage1' / 'metrics.jsonl')
rows = [json.loads(l) for l in p.read_text().splitlines() if l.strip()]
rec = [r['kip_rec'] for r in rows if 'kip_rec' in r]
first, last = sum(rec[:20])/20, sum(rec[-50:])/50
print(f'first 20 mean {first:.3f} | last 50 mean {last:.3f} | ratio {last/first:.2f}')
assert last < 0.6 * first, (
    f'STOP: L_KIP_rec did not roughly halve ({first:.3f} -> {last:.3f}). '
    'Stage 2 would rank a badly-trained e_O and still hand you a publishable '
    'number. This arm has no result until stage 1 converges.')

"""## Stage 2

### A2 — Plain-TSM Control
"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# 
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# S=2024
# 
# # --- A2: plain-TSM control (run this one first; no stage 1, no flow) ---
# python -m core.train \
#   --set train.stage=2 --set train.amp=true --set data.dataset=MSAD-full \
#   --set train.num_epochs=125 --set train.checkpoint_every_steps=100 \
#   --set train.seed=$S \
#   --set kip.gate_type=constant --set kip.const_shift_ratio=0.5 \
#   --set kip.disable_pmg=true \
#   --set loss.lambda_rec=0 --set loss.lambda_align=0 --set kip.use_lkin=false \
#   --data-dir "$KATVAD_DATA_ROOT/MSAD" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/MSAD_ncc" \
#   --knn-cache "$KATVAD_CACHE_ROOT/knn/MSAD_ncc/knn_cache.npz" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/MSAD_constant_s$S/stage2_kip_on"
#

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# 
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# S=2026
# 
# # --- A2: plain-TSM control (run this one first; no stage 1, no flow) ---
# python -m core.train \
#   --set train.stage=2 --set train.amp=true --set data.dataset=MSAD-full \
#   --set train.num_epochs=125 --set train.checkpoint_every_steps=100 \
#   --set train.seed=$S \
#   --set kip.gate_type=constant --set kip.const_shift_ratio=0.5 \
#   --set kip.disable_pmg=true \
#   --set loss.lambda_rec=0 --set loss.lambda_align=0 --set kip.use_lkin=false \
#   --data-dir "$KATVAD_DATA_ROOT/MSAD" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/MSAD_ncc" \
#   --knn-cache "$KATVAD_CACHE_ROOT/knn/MSAD_ncc/knn_cache.npz" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/MSAD_constant_s$S/stage2_kip_on"

"""### A0 — KIP-off baseline"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# S=2024        # re-run with 2025, then 2026
# 
# python -m core.train \
#   --set train.stage=2 --set train.amp=true --set data.dataset=MSAD-full \
#   --set train.num_epochs=125 --set train.checkpoint_every_steps=100 \
#   --set train.seed=$S \
#   --set kip.enabled=false \
#   --data-dir  "$KATVAD_DATA_ROOT/MSAD" \
#   --clip-dir  "$KATVAD_CACHE_ROOT/clip/MSAD_ncc" \
#   --knn-cache "$KATVAD_CACHE_ROOT/knn/MSAD_ncc/knn_cache.npz" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/MSAD_kipoff_s$S/stage2"

"""### A1 — the v3 model (Rank Gate)"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# 
# S=2024
# # --- A1: the v3 model ---
# python -m core.train \
#   --set train.stage=2 --set train.amp=true --set data.dataset=MSAD-full \
#   --set train.num_epochs=125 --set train.checkpoint_every_steps=100 \
#   --set train.seed=$S \
#   --set kip.gate_type=rank \
#   --init-weights "$KATVAD_OUTPUT_ROOT/MSAD_rank_s$S/stage1/checkpoint_last.pt" \
#   --data-dir "$KATVAD_DATA_ROOT/MSAD" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/MSAD_ncc" \
#   --flow-dir "$KATVAD_CACHE_ROOT/flow/v1/MSAD/MSAD-full" \
#   --knn-cache "$KATVAD_CACHE_ROOT/knn/MSAD_ncc/knn_cache.npz" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/MSAD_rank_s$S/stage2_kip_on"
#

"""### 5.2-A2b — Constant Gate, PMG genuinely trained"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# S=2024        # re-run with 2025, then 2026
# 
# python -m core.train \
#   --set train.stage=2 --set train.amp=true --set data.dataset=MSAD-full \
#   --set train.num_epochs=125 --set train.checkpoint_every_steps=100 \
#   --set train.seed=$S \
#   --set kip.gate_type=constant --set kip.const_shift_ratio=0.5 \
#   --init-weights "$KATVAD_OUTPUT_ROOT/MSAD_rank_s$S/stage1/checkpoint_last.pt" \
#   --data-dir  "$KATVAD_DATA_ROOT/MSAD" \
#   --clip-dir  "$KATVAD_CACHE_ROOT/clip/MSAD_ncc" \
#   --flow-dir  "$KATVAD_CACHE_ROOT/flow/v1/MSAD/MSAD-full" \
#   --knn-cache "$KATVAD_CACHE_ROOT/knn/MSAD_ncc/knn_cache.npz" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/MSAD_constant_pmg_s$S/stage2_kip_on"
#

"""### A3 — mlp_frozen, the bit-identical v1 bridge"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# S=2024        # re-run with 2025, then 2026
# 
# python -m core.train \
#   --set train.stage=2 --set train.amp=true --set data.dataset=MSAD-full \
#   --set train.num_epochs=125 --set train.checkpoint_every_steps=100 \
#   --set train.seed=$S \
#   --set kip.gate_type=mlp_frozen --set kip.gate_signal=flow_norm \
#   --init-weights "$KATVAD_OUTPUT_ROOT/MSAD_mlp_frozen_s$S/stage1/checkpoint_last.pt" \
#   --data-dir  "$KATVAD_DATA_ROOT/MSAD" \
#   --clip-dir  "$KATVAD_CACHE_ROOT/clip/MSAD_ncc" \
#   --flow-dir  "$KATVAD_CACHE_ROOT/flow/v1/MSAD/MSAD-full" \
#   --knn-cache "$KATVAD_CACHE_ROOT/knn/MSAD_ncc/knn_cache.npz" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/MSAD_mlp_frozen_s$S/stage2_kip_on"

"""### A4 — mlp_ste, the pure gradient intervention"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# S=2024        # re-run with 2025, then 2026
# 
# python -m core.train \
#   --set train.stage=2 --set train.amp=true --set data.dataset=MSAD-full \
#   --set train.num_epochs=125 --set train.checkpoint_every_steps=100 \
#   --set train.seed=$S \
#   --set kip.gate_type=mlp_ste --set kip.gate_signal=flow_norm \
#   --init-weights "$KATVAD_OUTPUT_ROOT/MSAD_mlp_frozen_s$S/stage1/checkpoint_last.pt" \
#   --data-dir  "$KATVAD_DATA_ROOT/MSAD" \
#   --clip-dir  "$KATVAD_CACHE_ROOT/clip/MSAD_ncc" \
#   --flow-dir  "$KATVAD_CACHE_ROOT/flow/v1/MSAD/MSAD-full" \
#   --knn-cache "$KATVAD_CACHE_ROOT/knn/MSAD_ncc/knn_cache.npz" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/MSAD_mlp_ste_s$S/stage2_kip_on"

"""# Evaluation

## A2 — plain-TSM control
"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# 
# S=2024        # re-run with 2025, then 2026
# CKPT="$KATVAD_OUTPUT_ROOT/MSAD_constant_s$S/stage2_kip_on/checkpoint_last.pt"
# 
# # --- MSAD-full, in-domain ---
# python -m core.evaluate \
#   --ckpt "$CKPT" \
#   --set data.dataset=MSAD-full \
#   --set kip.gate_type=constant --set kip.const_shift_ratio=0.5 \
#   --data-dir "$KATVAD_DATA_ROOT/MSAD" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/MSAD_ncc" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/MSAD_constant_s$S/eval_msad" \
#   --save-scores
# 
# python -m core.evaluate \
#   --ckpt "$CKPT" \
#   --set data.dataset=DoTA \
#   --set kip.gate_type=constant --set kip.const_shift_ratio=0.5 \
#   --data-dir "$KATVAD_DATA_ROOT/DoTA/labels_s8" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/DoTA_s8_ncc" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/DoTA_constant_s$S/eval_dota" \
#   --save-scores

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# 
# S=2026        # re-run with 2025, then 2026
# CKPT="$KATVAD_OUTPUT_ROOT/MSAD_constant_s$S/stage2_kip_on/checkpoint_last.pt"
# 
# # --- MSAD-full, in-domain ---
# python -m core.evaluate \
#   --ckpt "$CKPT" \
#   --set data.dataset=MSAD-full \
#   --set kip.gate_type=constant --set kip.const_shift_ratio=0.5 \
#   --data-dir "$KATVAD_DATA_ROOT/MSAD" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/MSAD_ncc" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/MSAD_constant_s$S/eval_msad" \
#   --save-scores
# 
# python -m core.evaluate \
#   --ckpt "$CKPT" \
#   --set data.dataset=DoTA \
#   --set kip.gate_type=constant --set kip.const_shift_ratio=0.5 \
#   --data-dir "$KATVAD_DATA_ROOT/DoTA/labels_s8" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/DoTA_s8_ncc" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/DoTA_constant_s$S/eval_dota" \
#   --save-scores

"""## A0 — KIP-off baseline"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# S=2024        # re-run with 2025, then 2026
# CKPT="$KATVAD_OUTPUT_ROOT/MSAD_kipoff_s$S/stage2/checkpoint_last.pt"
# 
# # --- MSAD-full, in-domain ---
# python -m core.evaluate \
#   --ckpt "$CKPT" \
#   --set data.dataset=MSAD-full --set kip.enabled=false \
#   --data-dir "$KATVAD_DATA_ROOT/MSAD" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/MSAD_ncc" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/MSAD_kipoff_s$S/eval_msad" \
#   --save-scores
# 
# # --- DoTA, zero-shot ---
# python -m core.evaluate \
#   --ckpt "$CKPT" \
#   --set data.dataset=DoTA --set kip.enabled=false \
#   --data-dir "$KATVAD_DATA_ROOT/DoTA/labels_s8" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/DoTA_s8_ncc" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/DoTA_kipoff_s$S/eval_dota" \
#   --save-scores

import numpy as np, pathlib, os

EXPECTED = {                      # gate_type -> (min span, max span) of 128
    'rank':       (100, 128),
    'mlp_frozen': (0, 8),
    'mlp_ste':    (0, 8),         # forward bit-identical to mlp_frozen
    'constant':   (0, 0),
}

def check(eval_dir: str, gate_type: str, n: int = 200) -> None:
    d = pathlib.Path(os.environ['KATVAD_OUTPUT_ROOT']) / eval_dir / 'scores'
    files = sorted(d.glob('*.npz'))[:n]
    assert files, f'no scores in {d}'
    spans, means, ratios = [], [], []
    for p in files:
        z = np.load(p)
        assert 'kip_s' in z, f'{p.name}: no kip_s — KIP-off arm, or --dump-kip-diag was off'
        s = z['kip_s'].astype(np.int32)
        spans.append(s.max() - s.min()); means.append(s.mean())
        ratios.append(float(z['kip_gate_ratio'].mean()))
    lo, hi = EXPECTED[gate_type]
    span_mean = float(np.mean(spans))
    print(f'{eval_dir}: span mean {span_mean:.1f} (min {min(spans)}, max {max(spans)}) '
          f'of 128 | s mean {np.mean(means):.1f} | ratio mean {np.mean(ratios):.3f}')
    assert lo <= span_mean <= hi, (
        f'GATE MISMATCH: {eval_dir} was scored as {gate_type!r} but span '
        f'{span_mean:.1f} is outside [{lo}, {hi}]. This eval is VOID — do not '
        f'read its AUC.')

S = 2024
for gate, run in [('constant', 'constant'), ('rank', 'rank'),
                  ('constant', 'constant_pmg'), ('mlp_frozen', 'mlp_frozen'),
                  ('mlp_ste', 'mlp_ste')]:
    for bench, root in [('eval_msad', 'MSAD'), ('eval_dota', 'DoTA')]:
        d = f'{root}_{run}_s{S}/{bench}'
        if (pathlib.Path(os.environ['KATVAD_OUTPUT_ROOT'])/d/'scores').is_dir():
            check(d, gate)

"""## A1 — the v3 model (rank gate)"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# S=2024        # re-run with 2025, then 2026
# CKPT="$KATVAD_OUTPUT_ROOT/MSAD_rank_s$S/stage2_kip_on/checkpoint_last.pt"
# 
# # --- MSAD-full, in-domain ---
# python -m core.evaluate \
#   --ckpt "$CKPT" \
#   --set data.dataset=MSAD-full --set kip.gate_type=rank \
#   --data-dir "$KATVAD_DATA_ROOT/MSAD" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/MSAD_ncc" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/MSAD_rank_s$S/eval_msad" \
#   --save-scores
# 
# # --- DoTA, zero-shot ---
# python -m core.evaluate \
#   --ckpt "$CKPT" \
#   --set data.dataset=DoTA --set kip.gate_type=rank \
#   --data-dir "$KATVAD_DATA_ROOT/DoTA/labels_s8" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/DoTA_s8_ncc" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/DoTA_rank_s$S/eval_dota" \
#   --save-scores
#

"""## A2b — constant gate, PMG trained"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# S=2024        # re-run with 2025, then 2026
# CKPT="$KATVAD_OUTPUT_ROOT/MSAD_constant_pmg_s$S/stage2_kip_on/checkpoint_last.pt"
# 
# # --- MSAD-full, in-domain ---
# python -m core.evaluate \
#   --ckpt "$CKPT" \
#   --set data.dataset=MSAD-full \
#   --set kip.gate_type=constant --set kip.const_shift_ratio=0.5 \
#   --data-dir "$KATVAD_DATA_ROOT/MSAD" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/MSAD_ncc" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/MSAD_constant_pmg_s$S/eval_msad" \
#   --save-scores
# 
# # --- DoTA, zero-shot ---
# python -m core.evaluate \
#   --ckpt "$CKPT" \
#   --set data.dataset=DoTA \
#   --set kip.gate_type=constant --set kip.const_shift_ratio=0.5 \
#   --data-dir "$KATVAD_DATA_ROOT/DoTA/labels_s8" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/DoTA_s8_ncc" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/DoTA_constant_pmg_s$S/eval_dota" \
#   --save-scores
#

"""## A3 — mlp_frozen, the v1 bridge"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# S=2024        # re-run with 2025, then 2026
# CKPT="$KATVAD_OUTPUT_ROOT/MSAD_mlp_frozen_s$S/stage2_kip_on/checkpoint_last.pt"
# 
# # --- MSAD-full, in-domain ---
# python -m core.evaluate \
#   --ckpt "$CKPT" \
#   --set data.dataset=MSAD-full \
#   --set kip.gate_type=mlp_frozen --set kip.gate_signal=flow_norm \
#   --data-dir "$KATVAD_DATA_ROOT/MSAD" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/MSAD_ncc" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/MSAD_mlp_frozen_s$S/eval_msad" \
#   --save-scores
# 
# # --- DoTA, zero-shot ---
# python -m core.evaluate \
#   --ckpt "$CKPT" \
#   --set data.dataset=DoTA \
#   --set kip.gate_type=mlp_frozen --set kip.gate_signal=flow_norm \
#   --data-dir "$KATVAD_DATA_ROOT/DoTA/labels_s8" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/DoTA_s8_ncc" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/DoTA_mlp_frozen_s$S/eval_dota" \
#   --save-scores
#

"""## A4 — mlp_ste, the gradient intervention"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# S=2024        # re-run with 2025, then 2026
# CKPT="$KATVAD_OUTPUT_ROOT/MSAD_mlp_ste_s$S/stage2_kip_on/checkpoint_last.pt"
# 
# # --- MSAD-full, in-domain ---
# python -m core.evaluate \
#   --ckpt "$CKPT" \
#   --set data.dataset=MSAD-full \
#   --set kip.gate_type=mlp_ste --set kip.gate_signal=flow_norm \
#   --data-dir "$KATVAD_DATA_ROOT/MSAD" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/MSAD_ncc" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/MSAD_mlp_ste_s$S/eval_msad" \
#   --save-scores
# 
# # --- DoTA, zero-shot ---
# python -m core.evaluate \
#   --ckpt "$CKPT" \
#   --set data.dataset=DoTA \
#   --set kip.gate_type=mlp_ste --set kip.gate_signal=flow_norm \
#   --data-dir "$KATVAD_DATA_ROOT/DoTA/labels_s8" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/DoTA_s8_ncc" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/DoTA_mlp_ste_s$S/eval_dota" \
#   --save-scores
#

"""## Rescore"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# 
# for d in "$KATVAD_OUTPUT_ROOT"/MSAD_*_s*/eval_msad \
#          "$KATVAD_OUTPUT_ROOT"/DoTA_*_s*/eval_dota \
#          "$KATVAD_OUTPUT_ROOT"/DoTA_gate_a/gate_a; do
#   [ -d "$d/scores" ] && python -m core.tools.rescore --run-dir "$d"
# done

