# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IVYzSxvnQl9h7dHfxTN7r9UigIssIqpI

# Train on DADA dataset V3
"""

from google.colab import drive
drive.mount("/content/drive")

import os

PROJECT_ROOT = "/content/drive/MyDrive/Thesis"
os.makedirs(PROJECT_ROOT, exist_ok=True)
os.environ["PROJECT_ROOT"] = PROJECT_ROOT
print("Project root:", PROJECT_ROOT)

!pip install -q \
  "transformers==4.56.*" \
  "av>=12" "einops>=0.8" "faiss-cpu==1.14.3" "gdown>=5" \
  "matplotlib>=3.9" "opencv-python==4.11.*" "pyyaml>=6" \
  "requests>=2.32" "scikit-learn>=1.5" "torchmetrics>=1.4" "tqdm>=4.66"

import faiss, numpy, torch, transformers
from transformers import CLIPTextModel
print('torch', torch.__version__, '| transformers', transformers.__version__,
      '| numpy', numpy.__version__, '| faiss', faiss.__version__)
print('text_model present:', 'text_model' in CLIPTextModel.__init__.__code__.co_names)

import os

DRIVE = '/content/drive/MyDrive/Thesis'
DRIVE_V3 = '/content/drive/MyDrive/Thesis-V3'

os.environ['KATVAD_DATA_ROOT']   = f'{DRIVE}/data'
os.environ['KATVAD_CACHE_ROOT']  = f'{DRIVE}/cache'
os.environ['KATVAD_CKPT_ROOT']   = f'{DRIVE}/ckpts'
os.environ['KATVAD_OUTPUT_ROOT'] = f'{DRIVE_V3}/outputs'
for v in ('KATVAD_DATA_ROOT', 'KATVAD_CACHE_ROOT', 'KATVAD_CKPT_ROOT', 'KATVAD_OUTPUT_ROOT'):
    os.makedirs(os.environ[v], exist_ok=True)

"""# Unzip"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# set -e
# mkdir -p /content/dada
# df -h /content | tail -1
# unzip -q "$KATVAD_DATA_ROOT/DADA2000/archive.zip" -d /content/dada
# ls /content/dada           # expect: Cleaned_Metadata.csv 0_Non_Ego_Fault 0_Normal_Driving

import os
ROOT = '/content/dada'
for d in ('0_Non_Ego_Fault', '0_Normal_Driving', '1_Ego_Fault'):
    folders = sorted(os.listdir(f'{ROOT}/{d}')) if os.path.isdir(f'{ROOT}/{d}') else []
    empty = [f for f in folders if not os.listdir(f'{ROOT}/{d}/{f}')]
    print(f'{d:18s} folders={len(folders):5d}  empty={len(empty):3d}  {empty[:3]}')
    assert not empty, f'{d}: empty folders = truncated unzip; re-run §3'

import csv, os
ROOT = '/content/dada'
have = {}
for d in ('0_Non_Ego_Fault', '1_Ego_Fault'):
    have[d] = set(os.listdir(f'{ROOT}/{d}'))

import re
def type_vid(name):
    m = re.match(r'^type(\d+)_vid(\d+)$', name)
    return (int(m.group(1)), int(m.group(2))) if m else None

on_disk = {d: {type_vid(n) for n in have[d] if type_vid(n)} for d in have}
missing = []
with open(f'{ROOT}/Cleaned_Metadata.csv', newline='', encoding='utf-8') as fh:
    for row in csv.DictReader(fh):
        if row['whether an accident occurred (1/0)'].strip() != '1':
            continue
        key = (int(row['type']), int(row['video']))
        d = row['Fault_Label'].strip()
        if key not in on_disk.get(d, set()):
            missing.append((d, key))
print(f'{len(missing)} CSV rows have no matching folder', missing[:5])
assert not missing, 'core.data.dada will raise on these; fix the unzip first (or pass --allow-missing-frames)'

import os, re
d = '/content/dada/0_Non_Ego_Fault'
sample = sorted(os.listdir(d))[0]
names = sorted(os.listdir(f'{d}/{sample}'))
print(sample, len(names), names[:5], '...', names[-3:])
lex = list(names)
num = sorted(names, key=lambda n: int(re.sub(r'\D', '', n) or 0))
print('lexicographic == numeric order:', lex == num)

"""# Build labels"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# 
# python -m core.data.dada \
#   --metadata   /content/dada/Cleaned_Metadata.csv \
#   --frames-dir /content/dada \
#   --out-dir    "$KATVAD_DATA_ROOT/DADA2000" \
#   --flat-frames-dir /content/dada_flat \
#   --stride 8 --seed 2024 \
#   --test-ratio-abnormal 0.2 --test-ratio-normal 0.2

import json, os
D = f"{os.environ['KATVAD_DATA_ROOT']}/DADA2000"
tr = json.load(open(f'{D}/labels_train.json'))
te = json.load(open(f'{D}/frame_labels_test.json'))
A, N = sum(tr.values()), len(tr) - sum(tr.values())
print(f'train {len(tr)} ({A} abnormal / {N} normal)')
print(f'test  {len(te)} ({sum(1 for v in te.values() if any(v))} with a positive frame)')
assert A and N, 'DVSFeatureDataset needs both classes'
assert not (set(tr) & set(te)), 'LEAK: an id is in both splits'
frac_normal = sum(1 for v in te.values() if not any(v)) / len(te)
print(f'test normal fraction {frac_normal:.3f}  -> score-norm auto resolves to '
      f'{"minmax" if frac_normal < 0.05 else "RAW"}')

"""# CLIP Extraction"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# 
# python -m core.tools.extract_clip_features \
#   --frames-dir /content/dada_flat \
#   --dataset DADA2000 --stride 8 --batch-size 64 --device cuda \
#   --no-center-crop \
#   --output-dir "$KATVAD_CACHE_ROOT/clip/DADA2000"

import os, json, numpy as np
C = f"{os.environ['KATVAD_CACHE_ROOT']}/clip/DADA2000"
D = f"{os.environ['KATVAD_DATA_ROOT']}/DADA2000"
have = {p[:-4] for p in os.listdir(C) if p.endswith('.npy')}
te = json.load(open(f'{D}/frame_labels_test.json'))
print(f'{len(have)} feature files')
bad = [(v, len(te[v]), len(np.load(f'{C}/{v}.npy'))) for v in te
       if v in have and len(np.load(f'{C}/{v}.npy')) != len(te[v])]
print('length mismatches vs frame labels:', len(bad), bad[:3])
assert not bad, 'feature rows must line up with label rows, one per sampled frame'

"""# Extract RAFT"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# 
# python -m core.flow.raft_extract \
#   --frames-dir /content/dada_flat \
#   --ids-file  "$KATVAD_DATA_ROOT/DADA2000/train_ids.txt" \
#   --dataset DADA2000 \
#   --cache-root "$KATVAD_CACHE_ROOT/flow/v1" \
#   --stride 8 --batch-size 8 --device cuda

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# 
# python -m core.data.knn_cache \
#   --data-dir "$KATVAD_DATA_ROOT/DADA2000" --dataset DADA2000 \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/DADA2000" \
#   --output   "$KATVAD_CACHE_ROOT/knn/DADA2000/knn_cache.npz" \
#   --motion-key

"""# Training

## Reproduce the baseline
"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# 
# python -m core.evaluate \
#   --baseline-ckpt "$KATVAD_CKPT_ROOT/best.ckpt" \
#   --set kip.enabled=false --set data.dataset=DADA2000 \
#   --data-dir "$KATVAD_DATA_ROOT/DADA2000" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/DADA2000" \
#   --score-norm auto \
#   --output-dir "$KATVAD_OUTPUT_ROOT/DADA2000/gate_d0" --save-scores

import json, math, os
tr = json.load(open(f"{os.environ['KATVAD_DATA_ROOT']}/DADA2000/labels_train.json"))
A = sum(tr.values())
BATCH, TARGET_STEPS = 64, 500
spe = math.ceil(2 * A / BATCH)
print(f'{A} abnormal -> len {2*A} -> {spe} steps/epoch')
print(f'num_epochs for ~{TARGET_STEPS} steps: {math.ceil(TARGET_STEPS / spe)}')

"""## Plain TSM"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# S=2025 ; E=20
# 
# python -m core.train \
#   --set train.stage=2 --set train.amp=true --set data.dataset=DADA2000 \
#   --set data.is_egocentric=true \
#   --set train.num_epochs=$E --set train.checkpoint_every_steps=100 \
#   --set train.seed=$S \
#   --set kip.gate_type=constant --set kip.const_shift_ratio=0.5 \
#   --set kip.disable_pmg=true \
#   --set loss.lambda_rec=0 --set loss.lambda_align=0 --set kip.use_lkin=false \
#   --data-dir  "$KATVAD_DATA_ROOT/DADA2000" \
#   --clip-dir  "$KATVAD_CACHE_ROOT/clip/DADA2000" \
#   --knn-cache "$KATVAD_CACHE_ROOT/knn/DADA2000/knn_cache.npz" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/DADA2000/constant_s$S/stage2_kip_on"

"""## Baseline KIP-off"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# S=2024 ; E=20
# 
# python -m core.train \
#   --set train.stage=2 --set train.amp=true --set data.dataset=DADA2000 \
#   --set data.is_egocentric=true \
#   --set train.num_epochs=$E --set train.checkpoint_every_steps=100 \
#   --set train.seed=$S \
#   --set kip.enabled=false \
#   --data-dir  "$KATVAD_DATA_ROOT/DADA2000" \
#   --clip-dir  "$KATVAD_CACHE_ROOT/clip/DADA2000" \
#   --knn-cache "$KATVAD_CACHE_ROOT/knn/DADA2000/knn_cache.npz" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/DADA2000/kipoff_s$S/stage2"

"""## Gate - Parameter free"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# S=2024 ; E=20
# 
# python -m core.train \
#   --set train.stage=1 --set data.dataset=DADA2000 --set data.is_egocentric=true \
#   --set train.num_epochs=$E --set train.seed=$S \
#   --set kip.gate_type=rank \
#   --data-dir  "$KATVAD_DATA_ROOT/DADA2000" \
#   --clip-dir  "$KATVAD_CACHE_ROOT/clip/DADA2000" \
#   --flow-dir  "$KATVAD_CACHE_ROOT/flow/v1/DADA2000" \
#   --knn-cache "$KATVAD_CACHE_ROOT/knn/DADA2000/knn_cache.npz" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/DADA2000/rank_s$S/stage1"

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# S=2024 ; E=20
# 
# python -m core.train \
#   --set train.stage=2 --set train.amp=true --set data.dataset=DADA2000 \
#   --set data.is_egocentric=true \
#   --set train.num_epochs=$E --set train.checkpoint_every_steps=100 \
#   --set train.seed=$S \
#   --set kip.gate_type=rank \
#   --init-weights "$KATVAD_OUTPUT_ROOT/DADA2000/rank_s$S/stage1/checkpoint_last.pt" \
#   --data-dir  "$KATVAD_DATA_ROOT/DADA2000" \
#   --clip-dir  "$KATVAD_CACHE_ROOT/clip/DADA2000" \
#   --flow-dir  "$KATVAD_CACHE_ROOT/flow/v1/DADA2000" \
#   --knn-cache "$KATVAD_CACHE_ROOT/knn/DADA2000/knn_cache.npz" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/DADA2000/rank_s$S/stage2_kip_on"

"""## MLP-frozen"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# S=2024 ; E=20
# 
# python -m core.train \
#   --set train.stage=1 --set data.dataset=DADA2000 \
#   --set data.is_egocentric=true \
#   --set train.num_epochs=$E --set train.seed=$S \
#   --set kip.gate_type=mlp_frozen --set kip.gate_signal=flow_norm \
#   --data-dir  "$KATVAD_DATA_ROOT/DADA2000" \
#   --clip-dir  "$KATVAD_CACHE_ROOT/clip/DADA2000" \
#   --flow-dir  "$KATVAD_CACHE_ROOT/flow/v1/DADA2000" \
#   --knn-cache "$KATVAD_CACHE_ROOT/knn/DADA2000/knn_cache.npz" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/DADA2000/mlp_frozen_s$S/stage1"

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# S=2024 ; E=20
# 
# python -m core.train \
#   --set train.stage=2 --set train.amp=true --set data.dataset=DADA2000 \
#   --set data.is_egocentric=true \
#   --set train.num_epochs=$E --set train.checkpoint_every_steps=100 \
#   --set train.seed=$S \
#   --set kip.gate_type=mlp_frozen --set kip.gate_signal=flow_norm \
#   --init-weights "$KATVAD_OUTPUT_ROOT/DADA2000/mlp_frozen_s$S/stage1/checkpoint_last.pt" \
#   --data-dir  "$KATVAD_DATA_ROOT/DADA2000" \
#   --clip-dir  "$KATVAD_CACHE_ROOT/clip/DADA2000" \
#   --flow-dir  "$KATVAD_CACHE_ROOT/flow/v1/DADA2000" \
#   --knn-cache "$KATVAD_CACHE_ROOT/knn/DADA2000/knn_cache.npz" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/DADA2000/mlp_frozen_s$S/stage2_kip_on"

"""## Constant - PMG"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# S=2024 ; E=20
# 
# python -m core.train \
#   --set train.stage=2 --set train.amp=true --set data.dataset=DADA2000 \
#   --set data.is_egocentric=true \
#   --set train.num_epochs=$E --set train.checkpoint_every_steps=100 \
#   --set train.seed=$S \
#   --set kip.gate_type=constant --set kip.const_shift_ratio=0.5 \
#   --init-weights "$KATVAD_OUTPUT_ROOT/DADA2000/rank_s$S/stage1/checkpoint_last.pt" \
#   --data-dir  "$KATVAD_DATA_ROOT/DADA2000" \
#   --clip-dir  "$KATVAD_CACHE_ROOT/clip/DADA2000" \
#   --flow-dir  "$KATVAD_CACHE_ROOT/flow/v1/DADA2000" \
#   --knn-cache "$KATVAD_CACHE_ROOT/knn/DADA2000/knn_cache.npz" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/DADA2000/constant_pmg_s$S/stage2_kip_on"

"""## MPL - STE"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# S=2024 ; E=20
# 
# python -m core.train \
#   --set train.stage=2 --set train.amp=true --set data.dataset=DADA2000 \
#   --set data.is_egocentric=true \
#   --set train.num_epochs=$E --set train.checkpoint_every_steps=100 \
#   --set train.seed=$S \
#   --set kip.gate_type=mlp_ste --set kip.gate_signal=flow_norm \
#   --init-weights "$KATVAD_OUTPUT_ROOT/DADA2000/mlp_frozen_s$S/stage1/checkpoint_last.pt" \
#   --data-dir  "$KATVAD_DATA_ROOT/DADA2000" \
#   --clip-dir  "$KATVAD_CACHE_ROOT/clip/DADA2000" \
#   --flow-dir  "$KATVAD_CACHE_ROOT/flow/v1/DADA2000" \
#   --knn-cache "$KATVAD_CACHE_ROOT/knn/DADA2000/knn_cache.npz" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/DADA2000/mlp_ste_s$S/stage2_kip_on"

"""# Evaluation"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# S=2025
# CKPT="$KATVAD_OUTPUT_ROOT/DADA2000/constant_s$S/stage2_kip_on/checkpoint_last.pt"
# GATE="--set kip.gate_type=constant --set kip.const_shift_ratio=0.5"
# 
# # --- DADA-2000, in-domain ---
# python -m core.evaluate --ckpt "$CKPT" $GATE \
#   --set data.dataset=DADA2000 \
#   --data-dir "$KATVAD_DATA_ROOT/DADA2000" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/DADA2000" \
#   --score-norm auto --save-scores \
#   --output-dir "$KATVAD_OUTPUT_ROOT/DADA2000/constant_s$S/eval_dada"

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# S=2025
# CKPT="$KATVAD_OUTPUT_ROOT/DADA2000/constant_s$S/stage2_kip_on/checkpoint_last.pt"
# GATE="--set kip.gate_type=constant --set kip.const_shift_ratio=0.5"
# 
# python -m core.evaluate --ckpt "$CKPT" $GATE \
#   --set data.dataset=DoTA \
#   --data-dir "$KATVAD_DATA_ROOT/DoTA/labels_s8" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/DoTA_s8_ncc" \
#   --score-norm auto --save-scores \
#   --output-dir "$KATVAD_OUTPUT_ROOT/DADA2000/constant_s$S/eval_dota"

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# S=2024
# CKPT="$KATVAD_OUTPUT_ROOT/DADA2000/kipoff_s$S/stage2/checkpoint_last.pt"
# GATE="--set kip.enabled=false"
# 
# # --- DADA-2000, in-domain ---
# python -m core.evaluate --ckpt "$CKPT" $GATE \
#   --set data.dataset=DADA2000 \
#   --data-dir "$KATVAD_DATA_ROOT/DADA2000" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/DADA2000" \
#   --score-norm auto --save-scores \
#   --output-dir "$KATVAD_OUTPUT_ROOT/DADA2000/kipoff_s$S/eval_dada"

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# S=2024
# CKPT="$KATVAD_OUTPUT_ROOT/DADA2000/kipoff_s$S/stage2/checkpoint_last.pt"
# GATE="--set kip.enabled=false"
# 
# # --- DoTA-2000, cross-domain ---
# python -m core.evaluate --ckpt "$CKPT" $GATE \
#   --set data.dataset=DoTA \
#   --data-dir "$KATVAD_DATA_ROOT/DoTA/labels_s8" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/DoTA_s8_ncc" \
#   --score-norm auto --save-scores \
#   --output-dir "$KATVAD_OUTPUT_ROOT/DADA2000/kipoff_s$S/eval_dota"

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# S=2024
# CKPT="$KATVAD_OUTPUT_ROOT/DADA2000/rank_s$S/stage2_kip_on/checkpoint_last.pt"
# 
# python -m core.evaluate \
#   --ckpt "$CKPT" \
#   --set data.dataset=DoTA --set kip.gate_type=rank \
#   --data-dir "$KATVAD_DATA_ROOT/DoTA/labels_s8" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/DoTA_s8_ncc" \
#   --output-dir "$KATVAD_OUTPUT_ROOT/DADA2000/rank_s$S/eval_dota" \
#   --save-scores

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# S=2024
# CKPT="$KATVAD_OUTPUT_ROOT/DADA2000/rank_s$S/stage2_kip_on/checkpoint_last.pt"
# 
# python -m core.evaluate \
#   --ckpt "$CKPT" \
#   --set data.dataset=DADA2000 \
#   --set kip.gate_type=rank \
#   --data-dir "$KATVAD_DATA_ROOT/DADA2000" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/DADA2000" \
#   --score-norm auto --save-scores \
#   --output-dir "$KATVAD_OUTPUT_ROOT/DADA2000/rank_s$S/eval_dada"

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# S=2024
# CKPT="$KATVAD_OUTPUT_ROOT/DADA2000/mlp_frozen_s$S/stage2_kip_on/checkpoint_last.pt"
# GATE="--set kip.gate_type=mlp_frozen --set kip.gate_signal=flow_norm"
# 
# # --- DoTA-2000, cross-domain ---
# python -m core.evaluate --ckpt "$CKPT" $GATE \
#   --set data.dataset=DoTA \
#   --data-dir "$KATVAD_DATA_ROOT/DoTA/labels_s8" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/DoTA_s8_ncc" \
#   --score-norm auto --save-scores \
#   --output-dir "$KATVAD_OUTPUT_ROOT/DADA2000/mlp_frozen_s$S/eval_dota"
#

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# S=2024
# CKPT="$KATVAD_OUTPUT_ROOT/DADA2000/mlp_frozen_s$S/stage2_kip_on/checkpoint_last.pt"
# GATE="--set kip.gate_type=mlp_frozen --set kip.gate_signal=flow_norm"
# 
# # --- DADA-2000, in-domain ---
# python -m core.evaluate --ckpt "$CKPT" $GATE \
#   --set data.dataset=DADA2000 \
#   --data-dir "$KATVAD_DATA_ROOT/DADA2000" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/DADA2000" \
#   --score-norm auto --save-scores \
#   --output-dir "$KATVAD_OUTPUT_ROOT/DADA2000/mlp_frozen_s$S/eval_dada"

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# S=2024
# CKPT="$KATVAD_OUTPUT_ROOT/DADA2000/constant_pmg_s$S/stage2_kip_on/checkpoint_last.pt"
# GATE="--set kip.gate_type=constant --set kip.const_shift_ratio=0.5"
# 
# # --- DADA-2000, in-domain ---
# python -m core.evaluate --ckpt "$CKPT" $GATE \
#   --set data.dataset=DADA2000 \
#   --data-dir "$KATVAD_DATA_ROOT/DADA2000" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/DADA2000" \
#   --score-norm auto --save-scores \
#   --output-dir "$KATVAD_OUTPUT_ROOT/DADA2000/constant_pmg_s$S/eval_dada"

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# S=2024
# CKPT="$KATVAD_OUTPUT_ROOT/DADA2000/constant_pmg_s$S/stage2_kip_on/checkpoint_last.pt"
# GATE="--set kip.gate_type=constant --set kip.const_shift_ratio=0.5"
# 
# # --- DoTA-2000, cross-domain ---
# python -m core.evaluate --ckpt "$CKPT" $GATE \
#   --set data.dataset=DoTA \
#   --data-dir "$KATVAD_DATA_ROOT/DoTA/labels_s8" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/DoTA_s8_ncc" \
#   --score-norm auto --save-scores \
#   --output-dir "$KATVAD_OUTPUT_ROOT/DADA2000/constant_pmg_s$S/eval_dota"

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# S=2024
# CKPT="$KATVAD_OUTPUT_ROOT/DADA2000/mlp_ste_s$S/stage2_kip_on/checkpoint_last.pt"
# GATE="--set kip.gate_type=mlp_ste --set kip.gate_signal=flow_norm"
# 
# # --- DADA-2000, in-domain ---
# python -m core.evaluate --ckpt "$CKPT" $GATE \
#   --set data.dataset=DADA2000 \
#   --data-dir "$KATVAD_DATA_ROOT/DADA2000" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/DADA2000" \
#   --score-norm auto --save-scores \
#   --output-dir "$KATVAD_OUTPUT_ROOT/DADA2000/mlp_ste_s$S/eval_dada"

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis-V3/kat-vad
# S=2024
# CKPT="$KATVAD_OUTPUT_ROOT/DADA2000/mlp_ste_s$S/stage2_kip_on/checkpoint_last.pt"
# GATE="--set kip.gate_type=mlp_ste --set kip.gate_signal=flow_norm"
# 
# # --- DoTA-2000, in-domain ---
# python -m core.evaluate --ckpt "$CKPT" $GATE \
#   --set data.dataset=DoTA \
#   --data-dir "$KATVAD_DATA_ROOT/DoTA/labels_s8" \
#   --clip-dir "$KATVAD_CACHE_ROOT/clip/DoTA_s8_ncc" \
#   --score-norm auto --save-scores \
#   --output-dir "$KATVAD_OUTPUT_ROOT/DADA2000/mlp_ste_s$S/eval_dota"

