# -*- coding: utf-8 -*-
"""evaluate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ueRkt2xwmtEeoiDqNJ5-MdouHiWso06J
"""

from google.colab import drive
drive.mount("/content/drive")

import os

PROJECT_ROOT = "/content/drive/MyDrive/Thesis"
os.makedirs(PROJECT_ROOT, exist_ok=True)
os.environ["PROJECT_ROOT"] = PROJECT_ROOT
print("Project root:", PROJECT_ROOT)

!pip install -q \
  "torch==2.4.*" "torchvision==0.19.*" "transformers==4.56.*" \
  "numpy<2" \
  "av>=12" "einops>=0.8" "faiss-cpu>=1.8" "gdown>=5" \
  "matplotlib>=3.9" "opencv-python==4.11.*" "pyyaml>=6" \
  "requests>=2.32" "scikit-learn>=1.5" "torchmetrics>=1.4" "tqdm>=4.66"

import os

DRIVE = '/content/drive/MyDrive/Thesis'
os.environ['KATVAD_DATA_ROOT']   = f'{DRIVE}/data'     # raw videos + label files
os.environ['KATVAD_CACHE_ROOT']  = f'{DRIVE}/cache'    # CLIP / flow / KNN caches
os.environ['KATVAD_CKPT_ROOT']   = f'{DRIVE}/ckpts'    # best.ckpt + our checkpoints
os.environ['KATVAD_OUTPUT_ROOT'] = f'{DRIVE}/outputs'  # eval results, plots, logs
for v in ('KATVAD_DATA_ROOT', 'KATVAD_CACHE_ROOT', 'KATVAD_CKPT_ROOT', 'KATVAD_OUTPUT_ROOT'):
    os.makedirs(os.environ[v], exist_ok=True)

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# 
# python -m core.tools.download clip

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# 
# python -m core.data.dota \
#   --metadata   "$KATVAD_DATA_ROOT/DoTA/metadata_val.json" \
#   --split-file "$KATVAD_DATA_ROOT/DoTA/val_split.txt" \
#   --frames-dir "$KATVAD_DATA_ROOT/DoTA/frames" --frames-subdir images \
#   --out-dir    "$KATVAD_DATA_ROOT/DoTA/labels_s8" \
#   --stride 8 --allow-missing-frames

"""## Extract CLIP features"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# 
# python -m core.tools.extract_clip_features \
#   --frames-dir "$KATVAD_DATA_ROOT/DoTA/frames" --frames-subdir images \
#   --ids-file "$KATVAD_DATA_ROOT/DoTA/labels_s8/test_ids.txt" \
#   --dataset DoTA --stride 1 --batch-size 64 --device cuda \
#   --no-center-crop \
#   --output-dir "$KATVAD_CACHE_ROOT/clip/DoTA_s1_ncc"

from pathlib import Path
import numpy as np, os

src = Path(os.environ['KATVAD_CACHE_ROOT']) / 'clip' / 'DoTA_s1_ncc'
dst = Path(os.environ['KATVAD_CACHE_ROOT']) / 'clip' / 'DoTA_s8_ncc'
dst.mkdir(parents=True, exist_ok=True)
for p in src.glob('*.npy'):
    np.save(dst / p.name, np.load(p)[::8])
print(len(list(dst.glob('*.npy'))), 'files')

"""## Reproduction baseline LaGoVAD"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# 
# DATA="$KATVAD_DATA_ROOT/DoTA/labels_s8"
# CLIP="$KATVAD_CACHE_ROOT/clip/DoTA_s8_ncc"
# OUT="$KATVAD_OUTPUT_ROOT/DoTA_ncc"
# 
# # Arm 1 — reference: LaGoVAD's released checkpoint (PreVAD-trained)
# python -m core.evaluate \
#   --baseline-ckpt "$KATVAD_CKPT_ROOT/best.ckpt" \
#   --set kip.enabled=false --set data.dataset=DoTA \
#   --data-dir "$DATA" --clip-dir "$CLIP" \
#   --output-dir "$OUT/gate_a" --save-scores

"""## MSAD-trained & KIP-off"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# 
# DATA="$KATVAD_DATA_ROOT/DoTA/labels_s8"
# CLIP="$KATVAD_CACHE_ROOT/clip/DoTA_s8_ncc"
# OUT="$KATVAD_OUTPUT_ROOT/DoTA_ncc"
# 
# # Arm 2 — our baseline (MSAD-trained, KIP off)
# python -m core.evaluate \
#   --ckpt "$KATVAD_OUTPUT_ROOT/MSAD_rcc/stage2_kip_off/checkpoint_last.pt" \
#   --set kip.enabled=false --set data.dataset=DoTA \
#   --data-dir "$DATA" --clip-dir "$CLIP" \
#   --output-dir "$OUT/eval_kip_off" --save-scores

"""## MSAD-trained & KIP-on"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# DATA="$KATVAD_DATA_ROOT/DoTA/labels_s8"
# CLIP="$KATVAD_CACHE_ROOT/clip/DoTA_s8_ncc"
# OUT="$KATVAD_OUTPUT_ROOT/DoTA_ncc"
# 
# # Arm 3 — ours + KIP (MSAD-trained)
# python -m core.evaluate \
#   --ckpt "$KATVAD_OUTPUT_ROOT/MSAD_rcc/stage2_kip_on/checkpoint_last.pt" \
#   --set data.dataset=DoTA \
#   --data-dir "$DATA" --clip-dir "$CLIP" \
#   --output-dir "$OUT/eval_kip_on" --save-scores

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Thesis/kat-vad
# 
# for d in gate_a eval_kip_off eval_kip_on; do
#   python -m core.tools.rescore --run-dir "$KATVAD_OUTPUT_ROOT/DoTA_ncc/$d"
# done

